### ISSUE TITLE
Latest tinymce version is 4.1.7

### ISSUE THREAD

**Issue by rbloor-mdsol** [spohlenz/tinymce-rails#167]
https://github.com/tinymce/tinymce/releases

Could you please create another release that points to 4.1.7?

**Comment by jheth** [comment]
Now 4.1.10

**Comment by rassom** [comment]
Now 4.2.1 - anybody working on updating ?

**Comment by spohlenz** [comment]
Apologies for the hiatus. I have some new updates (3.5.11, 4.1.10 and 4.2.1) as well as engine fixes and improvements planned for release later today.

**Comment by rassom** [comment]
Sounds good! Thanks :+1: :smiley:

**Comment by rassom** [comment]
Good job - thanks :+1:

**Comment by rassom** [comment]
PS. Works fine for me with config.tinymce.install = :compile on Heroku :dancers:
