### ISSUE TITLE
Is tinymce.yml hard-coded to be checked in config/tinymce.yml?

### ISSUE THREAD

**Issue by corroded** [spohlenz/tinymce-rails#176]
I am working on a Rails engine (4.2) that has tinymce. I added tinymce.yml in the engine's config file but it didn't produce the proper config I have there. After moving tinymce.yml into the app that is using the engine's config, it worked.

Directory structure is something like:

- main_app
  - app
  - config
    - tinymce.yml <-- works
  - vendor
    - gems
      - my_rails_engine_w_tinymce
        - config
          - tinymce.yml <-- doesn't work

(my engine is submoduled into my main_app's vendor/gems folder).

Shouldn't the expected behavior be that it checks for the yml file inside the engine since the engine is the one that explicitly uses tinymce? Or is this only failing because I vendored my engine into my app?

**Comment by spohlenz** [comment]
The latest releases (3.511, 4.1.10 and 4.2.1) now include a `config.tinymce.config_path` option which you can set within your engine's initializer to define a custom path to the config file.
