### ISSUE TITLE
Editor wont load in production env

### ISSUE THREAD

**Issue by Znow** [spohlenz/tinymce-rails#197]
Hi

In a production site, I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/265719/14103322/dbb72e62-f59f-11e5-8c7f-f64f6aa62f65.png)

Im loading the tinymce as below:

```
<%= tinymce_assets %>
<%= tinymce :language => "da" %>
```

I've aso tried to require 'tinymce' and 'tinymce-jquery' in the application.js file, without luck.

Kind regards

**Comment by Brotakuu** [comment]
Maybe your assets were not precompiled? Try running `rake assets:precompile`, then push to production.

**Comment by Znow** [comment]
They are compiled on deployment by capistrano :-)
