### ISSUE TITLE
Toolbar icons appearing vertically

### ISSUE THREAD

**Issue by dblencowe** [spohlenz/tinymce-rails#201]
Hi guys,

My icons have started appearing vertically and after hours of trying to figure out why I've been unable. Any advice you can offer would be great, thanks!

https://www.dropbox.com/s/fm0fks8wsedz4l5/Screenshot%202016-07-25%2020.43.13.png?dl=0

**Comment by Brotakuu** [comment]
Did you make css changes? if so, share those details.

**Comment by dblencowe** [comment]
No, there's nothing overriding the tinymce CSS unfortunately!

Thanks

**Comment by Brotakuu** [comment]
Could be a stylesheet conflict. Do you have a live version of it that you could link to? Or you could inspect the element using developer tools in your browser.

**Comment by dblencowe** [comment]
It seems there was a change in the config layout. I used to have the toolbar layout defined as below. Now it seems to only work when setting it along one line! Thanks.

`toolbar:
  - item1
  - item2`
