### ISSUE TITLE
After updateing to 4.5.1 bullist and numlist don't work

### ISSUE THREAD

**Issue by pmichna** [spohlenz/tinymce-rails#207]
My tinymce.yml:
```
menubar: false
toolbar:
  - styleselect fontsizeselect | tools | bold italic underline strikethrough | removeformat | alignleft aligncenter alignright | undo redo
  - link image | bullist numlist | outdent indent | table | code
plugins:
  - image
  - link
  - table
  - code
```

With `tinymce-rails` 4.4.3 everything works fine. After updating to 4.5.1 bullist and numlist buttons just don't appear in the editor.

**Comment by spohlenz** [comment]
Looks like you now need to add the `lists` plugin. See https://github.com/tinymce/tinymce/issues/3342.
