### ISSUE TITLE
install = :compile is required with react_on_rails

### ISSUE THREAD

**Issue by sigmike** [spohlenz/tinymce-rails#208]
> config.tinymce.install = :compile
> This method is intended to eventually become the default, so please try it if it suits your environment and report any issues.

I just wanted to report the opposite, that the default `:copy` install method fails when the [React on Rails gem](https://github.com/shakacode/react_on_rails) is installed.

On the first `assets:precompile` it seems to work but tinymce fails to load its icons. And all subsequent `assets:precompile` fail with this error:
```
Errno::ELOOP: Too many levels of symbolic links @ rb_sysopen - /[...]/public/assets/tinymce/plugins/emoticons/img/smiley-smile.gif
```

**Comment by spohlenz** [comment]
It looks like the react_on_rails gem is clobbering the `assets:precompile` which I don't think is good practice. However it looks like they do at least create symlinked non-digested assets (which is what the :compile method does in tinymce-rails). I gather that the :compile method does work properly with react_on_rails?

It is about time that :compile is made the default now -- I will look at changing that for the next release.
