### ISSUE TITLE
Mentions Plugin Missing

### ISSUE THREAD

**Issue by loganh0522** [spohlenz/tinymce-rails#211]
I just want to say thanks for developing a great gem to integrate TinyMce into rails. 

I have been using TinyMce gem for a project that I am working on and have noticed that the gem is missing the Mentions plugin. I have tried uninstalling and reinstalling the gem without any luck. 

I was wondering if anyone else has encountered this issue? 

Thanks for the help!!

**Comment by spohlenz** [comment]
The mentions plugin appears to be an enterprise-only feature (see https://www.tinymce.com/docs/plugins/mentions/#downloadingmentionsplugin). The `tinymce-rails` gem only bundles the community plugins.
