### ISSUE TITLE
NoMethodError (undefined method `permit' for "<p>23423</p>":String):

### ISSUE THREAD

**Issue by JorgeDDW** [spohlenz/tinymce-rails#215]
Any idea on whats the problem with this issue?
`NoMethodError (undefined method `permit' for "<p>23423</p>":String):`

**Comment by spohlenz** [comment]
Sounds like it might be a params issue in your controller, so I'd suggest starting there. You may not need a call to `params.require(..).permit(..)` if you're just passing in a single top-level param.
