### ISSUE TITLE
Why the layer plugin is not present?

### ISSUE THREAD

**Issue by IlkhamGaysin** [spohlenz/tinymce-rails#243]
I have been migrating from 3 version to 4 of tiny mce and haven't found layer plugin here but I have found it in documentation of 4.x version here 
[layer doc for 4.x](https://www.tinymce.com/docs/plugins/layer/)

**Comment by spohlenz** [comment]
I'm not sure why there the documentation is there, however it seems that the layer plugin is not a part of TinyMCE anymore (https://github.com/tinymce/tinymce/issues/3388). In any case, it does not come as part of the downloads from https://www.tinymce.com/download/ or exist in the repo at https://github.com/tinymce/tinymce/tree/master/src/plugins.

**Comment by IlkhamGaysin** [comment]
@spohlenz got it, thanks!
