### ISSUE TITLE
Uncaught ReferenceError: TinyMCERails is not define

### ISSUE THREAD

**Issue by poonkodi123** [spohlenz/tinymce-rails#252]

**Comment by poonkodi123** [comment]
Im using rails5 and ruby 2.3

Also try to follow this guide, with same results : https://alexanderpaterson.com/posts/using-the-tinymce-text-editor-in-a-rails-application

As i'm not able to find a solution (didn't find anything in the issues), i open a new issue.

**Comment by spohlenz** [comment]
It looks like the tutorial at https://alexanderpaterson.com/posts/using-the-tinymce-text-editor-in-a-rails-application is somewhat out of date.

The tinymce-rails gem has its own `tinymce.js` file which sets up the `TinyMCERails` module, and by creating `app/assets/javascripts/tinymce.js` this file is overridden.

If you want to continue with that tutorial, change the file name to something else, e.g. `app/assets/javascripts/editor.js`.
