### ISSUE TITLE
Getting 404 for assets/tinymce/skins/content/default/content.css with 5.x but not 4.x

### ISSUE THREAD

**Issue by sgelliott** [spohlenz/tinymce-rails#255]
Everything has been working perfectly with 4.x versions of the gem. Recently, when upgrading to 5.x (latest attempt 5.0.2) I started getting the following error in the browser...

tinymce.source.js:4341 GET /assets/tinymce/skins/content/default/content.css net::ERR_ABORTED 404 (Not Found)

Downgrading back to 4.9.3 solves the issue. Some notes below...

1. I have `config.tinymce.install = :copy` but have also tried `config.tinymce.install = :compile` - same results in both cases
2. TinyMCE seems to work fine even with the error for the most part. However, the "Paragraph" menu dropdown sometimes will not expand until the user refreshes the page. And generally, any error message should be addressed regardless. 
3. Turbolinks is active. But I don't see any indication that this would have an impact. Especially because everything was working with 4.x versions.
4. Read through documentation, open & closed issues, etc. but don't see any working solutions for this. What changed from 4.9.3 to 5.0.x which might create this issue? What can I try to solve for it?

Thank you in advance for any guidance. Happy to share more information as requested.

<img width="582" alt="tinymce 5 0 2-404-error" src="https://user-images.githubusercontent.com/7925160/53937342-aeca2700-4061-11e9-8a55-79238ef802fd.png">

**Comment by spohlenz** [comment]
Thank you for reporting. It looks like TinyMCE 5.x started packaging `.min.css` files rather than `.css`.

This should now be fixed in the 5.0.3 gem release.
