### ISSUE TITLE
Multiple toolbars are merged into a single bar

### ISSUE THREAD

**Issue by solomous** [spohlenz/tinymce-rails#256]
E.g. the following results in a single merged bar.

toolbar:
  - styleselect | bold italic | undo redo
  - image | link

(same if you use toolbar1, toolbar2 etc)

![Screen Shot 2019-05-06 at 12 48 40 pm](https://user-images.githubusercontent.com/6852467/57204804-51b90600-6ffd-11e9-805b-b3a11c103ed3.png)

**Comment by spohlenz** [comment]
It looks like this was an intentional upstream change.
See https://github.com/tinymce/tinymce/issues/4819 for the issue report and some potential workarounds.
