### ISSUE TITLE
Compatibility with Sprockets 4

### ISSUE THREAD

**Issue by brian-kephart** [spohlenz/tinymce-rails#264]
Since upgrading to Sprockets 4, I'm not getting the same results as before. Specifically, public/assets/tinymce does not get created when precompiling assets with
```ruby
Rails.application.config.assets.tinymce = :compile
```

**Comment by spohlenz** [comment]
Thank you for reporting. I've added a Sprockets 4 manifest in f305e3b6780a5237a544c0ddb84be32defcbd191 and released version 5.1.4.1.

For clarity, the configuration for the TinyMCE compilation should be:

```ruby
Rails.application.config.tinymce.install = :compile
```

which I'm assuming is just a typo.

**Comment by brian-kephart** [comment]
@spohlenz Thanks for the fix! It works well.

Is there any chance of backporting this to the 4.x branch? I'm a contributor to a Rails engine that relies on tinymce-rails, and we'd like to support Sprockets 4 without introducing the breaking changes required by 5.x.

**Comment by spohlenz** [comment]
Not a problem. I've just pushed 4.9.7.1 with a similar fix.

**Comment by brian-kephart** [comment]
Thanks! Fixing the older branch is above and beyond, I really appreciate it.
