### ISSUE TITLE
Rails 6: In assets we are missing content.min.css and skin.min.css

### ISSUE THREAD

**Issue by quantavi** [spohlenz/tinymce-rails#270]
tinymce-rails tries to load assets/tinymce/skins/trestle/skin.min.css, but file that gets created is under different location: assets/tinymce/skins/lightgray/skin.min.css. Same goes for content.min.css file. 
Is there any additional step needed for assets precompilation?
Thanks

**Comment by spohlenz** [comment]
This should now be fixed in the latest releases of trestle-tinymce.
