### ISSUE TITLE
Configuring init_instance_callback does not work with string or arrow function

### ISSUE THREAD

**Issue by ronald** [spohlenz/tinymce-rails#291]
Thanks for providing this plugin :smile: 

I've question / bug report.

my config looks like this:
``` yaml
default:
  init_instance_callback: "tinymce_after_init"
```

tinymce-rails generates this:
```javascript
TinyMCERails.configuration.default = {
  selector: "textarea.tinymce",
  cache_suffix: "?v=6.2.0",
  init_instance_callback: "tinymce_after_init"
};
TinyMCERails.initialize('default', {
  
});
```

The callback does not work as it is passed as string to TinyMCE.

Is there any other way to pass the callback?

Thx

**Comment by spohlenz** [comment]
Try setting `init_instance_callback` to a string beginning with `"function("`. The configuration should detect this and output it as a function rather than a string.

e.g.

```yaml
default:
  init_instance_callback: "function() { tinymce_after_init(); }"
```

**Comment by ronald** [comment]
This works. Thank you.

Is this documented somewhere or should i provide PR to README?

I already tried this before
```yaml
default:
  init_instance_callback: "() => tinymce_after_init()"
```
but Arrow function expression does not seem to be supported.

Does it make sense to support that as well?

**Comment by spohlenz** [comment]
Support for arrow functions has been added in 6363612.
