### ISSUE TITLE
TinyMCE is stripping HTML code for YouTube iFrame embed, therefore the embed is not displaying

### ISSUE THREAD

**Issue by danhodgins** [spohlenz/tinymce-rails#294]
First off, thank you for creating this gem. The integration with Rails has been relatively smooth. I know how much work it is to create and maintain a gem, so thank you to all who are involved.  

Context: TinyMCE-rails is working perfectly in my app except for one issue (below) 

Here are more details about this issue:

Issue: TinyMCE is stripping HTML code for YouTube iFrame embed, therefore the embed is not displaying.

Expected behaviour: YouTube embed code in TinyMCE text editor should display the YouTube video as expected in a Rails view for the Post#show action (post.html.erb). iFrame embed code should be visible when inspecting page source code. 

Actual behaviour: when I view source, I see empty paragraph tags where the iFrame embed code should be. 

What's happening: clearly, TinyMCE-Rails is somehow stripping the embed code. 

Since I only have a TinyMCE.yml file, I am not sure where to go to override the JS that is stripping the code. 

Any ideas are much appreciated. 

Again, thank you to the creators and maintainers of this gem for all of your hard work. 

-Dan H

**Comment by danhodgins** [comment]
My error, looks like I needed to look more closely at the documentation. Sorry about that.

**Comment by Faq** [comment]
Post also here solution if you can.
