### ISSUE TITLE
Rails 7 with Importmaps - TinyMCERails is not defined

### ISSUE THREAD

**Issue by phil-6** [spohlenz/tinymce-rails#306]
We have tried a LOT of options to try and get the tinymce-rails gem working with Rails 7 and Importmaps, almost every approach leads to `Uncaught ReferenceError: TinyMCERails is not defined` from wherever we call `<%= tinymce %>`

The approaches we have tried:
1. As per the documentation: Install Gem, `tinymce_assets` helper in application head etc. 
2. Not using the asset helper, and adding `import "tinymce"` to our application.js
3. Importing tinymce js from every conceivable location (including the root gem path) and then as above.

**Comment by sergey-arkhipov** [comment]
Working app with tinyMCE on Rails 7  [rails_tinyMCE](https://github.com/sergey-arkhipov/rails_tinyMCE)

**Comment by phil-6** [comment]
> Working app with tinyMCE on Rails 7 and importmap [rails_tinyMCE](https://github.com/sergey-arkhipov/rails_tinyMCE)

That was really helpful, that has helped scope the issue to Propshaft.

I'll close this as a duplicate of #303

**Comment by latecia94** [comment]
> > Working app with tinyMCE on Rails 7 and importmap [rails_tinyMCE](https://github.com/sergey-arkhipov/rails_tinyMCE)
> 
> That was really helpful, that has helped scope the issue to Propshaft.
> 
> I'll close this as a duplicate of #303

Hey @phil-6 Did you get this working with Propshaft? What solution did you find?

**Comment by phil-6** [comment]
@latecia94 no, sadly not. We moved to use [EditorJS](https://editorjs.io/) instead as we felt it was a better all-round solution

**Comment by spohlenz** [comment]
Propshaft has been added in #315. If you are able to test it out and share your experience, that would be great.
