### ISSUE TITLE
Wrong license on main branch (since version 7)

### ISSUE THREAD

**Issue by debanne** [spohlenz/tinymce-rails#311]
The license can't be MIT anymore (as the code of TinyMCE 7 is redistributed) and should be changed to [GNU General Public License Version 2 or later](http://www.gnu.org/licenses/gpl.html).

**Comment by spohlenz** [comment]
Thank you for bringing this to my attention. I'd briefly seen the license change but failed to consider how it would affect the licensing for this project.

I've gone ahead and updated the project license to be compatible, and re-released the gem.
