### ISSUE TITLE
Wrong styles applied to my layout after installing gem

### ISSUE THREAD

**Issue by dewey** [spohlenz/tinymce-rails#316]
I'm running into the issue that as soon as I add `gem 'tinymce-rails'` to my Gemfile and restart my server the existing layout is broken. The only changes I've done are installing the gem and adding this to my head:

```
<head>
  <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= tinymce_assets %>
  <script type="text/javascript" src="/assets/tinymce.js"></script>
</head>
```

If I'm removing the gem, everything works again. Is there any known issues with using it combined with Tailwind? That I can see the same style being applied multiple times seems a bit suspicious.

Thanks!

I can see the styles being injected in the header:
![Screenshot 2024-10-04 at 22 42 33 png@2x](https://github.com/user-attachments/assets/d0787f45-11c2-43af-b80a-65c267df6143)

MCE styles being loaded:
![Screenshot 2024-10-04 at 22 40 03 png@2x](https://github.com/user-attachments/assets/c8ae52ed-3000-4276-8d0d-3d99240749dd)

Lots of styles being applied to the body over and over again:

![Screenshot 2024-10-04 at 22 39 47 png@2x](https://github.com/user-attachments/assets/4eed990e-177e-4e38-9b1a-32c9c442e430)

**Comment by Faq** [comment]
Not much info provided, Gem/Rails version. Any online example?

**Comment by spohlenz** [comment]
You shouldn't need both of these lines:

```erb
  <%= tinymce_assets %>

  <script type="text/javascript" src="/assets/tinymce.js"></script>
```

Just including the call to `tinymce_assets` should automatically include the script tag for you. I expect that will fix the duplicated stylesheets being included, which hopefully in turn should fix the layout breakage.

**Comment by samvandamme** [comment]
I am having the same issue since using @rails/propshaft

**Comment by dewey** [comment]
> Not much info provided, Gem/Rails version. Any online example?

No online example but very standard Rails 8.0.0.alpha app and v7.3.0 of this gem.

**Comment by spohlenz** [comment]
This is definitely one where I'll need a reproduction example repo as I've been unable to replicate it myself.

I've uploaded my own example to https://github.com/spohlenz/TinyMCERails8 which is working. In spohlenz/TinyMCERails8@5ae3f16592029a1db6742dcc0e1c41f797617118 you'll find the code added onto a fresh Rails 8.0.0.beta1 application.

**Comment by dewey** [comment]
Hey @spohlenz, thanks for taking the time to reply here. I just created a minimal repo based on the following command and was able to reproduce the issue. As soon as the gem is installed the layout shifts.

```
rails new tinymce-tailwind-rails8 --main --javascript=esbuild --skip-test --css=tailwind --skip-bootsnap
```

You can see the "before tinymce" and "after tinymce" commits, and here's how it looks for me.

**Before:**

![Screenshot 2024-10-12 at 10 59 44 png@2x](https://github.com/user-attachments/assets/623ea1a0-0a6f-496c-80f6-d248d0faf378)

**After:**

![Screenshot 2024-10-12 at 11 00 40 png@2x](https://github.com/user-attachments/assets/5492111e-8478-4d24-a4a5-a49004083b45)

**Comment by spohlenz** [comment]
Looking back again at your original example, I see the line
```erb
<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
```

**Comment by spohlenz** [comment]
Further digging: that behavior is coming from https://github.com/rails/propshaft/blob/main/lib/propshaft/helper.rb#L21-L23

There doesn't appear to be any way to exclude railtie/engine assets when using `stylesheet_link_tag :all` so the only advice I can give is to use `:app` instead. It appears this is basically the reason that`:app` was introduced (see rails/propshaft#187 / rails/propshaft#190).

**Comment by dewey** [comment]
That's a very nice find, thanks for digging that up! That does indeed fix the issue, guess that's a new Rails 8 thing that needs to be documented, maybe others will stumble upon this discussion.

Thanks again for taking  the time to maintain this and for investigating this issue!
