### ISSUE TITLE
error: $("textarea").tinymce is not a function

### ISSUE THREAD

**Issue by dorajistyle** [spohlenz/tinymce-rails#37]
Hello, Thank you for offer nice gem plugins.
I've got a problem with using it.

I added below in Gemfile.
gem 'tinymce-rails'
And then run bundle install.

Add to my application.js:
//= require tinymce-jquery

<script src="/assets/tinymce/preinit.js?body=1" type="text/javascript"></script>

<script src="/assets/tinymce/tiny_mce_jquery.js?body=1" type="text/javascript"></script>

<script src="/assets/tinymce/jquery-tinymce.js?body=1" type="text/javascript"></script>

<script src="/assets/tinymce-jquery.js?body=1" type="text/javascript"></script>

These script files loaded well.

But when I tried below code to use tinymce, I got the Error message.

$(function() {
    $('textarea').tinymce({
      theme: 'advanced'
    });
  });

$("textarea").tinymce is not a function

How could I fix this problem?

Regards.

**Comment by AmirHoseinRh** [comment]
so how the problem solved?
