### ISSUE TITLE
Multiple Instance on same page

### ISSUE THREAD

**Issue by nazarhussain** [spohlenz/tinymce-rails#42]
Hi, Your gem is great in reference to including the tinnyMCE,

I was having an issue with your current version `3.4.8`, I want to have multiple tinnyMCE instances on the same page.

I tried it out as:

```
$('textarea.editor').tinymce({
            theme:'simple'
        });
```

This makes all textareas with editor available but when i post the form for each editor new text does not posted.

if i use it like

```
$("textarea.editor").live('focus', function () {
        $(this).tinymce({
            theme:'simple'
        });
    });
```

Every time i focus on any of the text-area, only the first text-area in the DOM is converted into the editor.

Why is i am facing such a behavior?

**Comment by lukerollans** [comment]
This isn't fixing the issue for me. My `textarea` tags have unique IDs, but changes going in to the TinyMCE editor are not being applied to the textarea.

Does anyone have any other insight?

**Comment by thegentleman100** [comment]
nazarhussain thank you, your comment really helped me!
