### ISSUE TITLE
using the helper method doesn't seem to work when using jQuery

### ISSUE THREAD

**Issue by holden** [spohlenz/tinymce-rails#51]
The helper  <%= tinymce %> which generates:

```
<script>
//<![CDATA[
tinyMCE.init({"mode":"textareas","theme":"advanced","editor_selector":"tinymce","theme_advanced_toolbar_location":"top","theme_advanced_toolbar_align":"left","theme_advanced_statusbar_location":"bottom","theme_advanced_buttons3_add":"tablecontrols,fullscreen","plugins":"table,fullscreen","language":"en"});
//]]>
</script>
```

returns a 'tinyMCE is not defined' error.

It works fine when I call it directly. ie:

```
jQuery ->
    $('.tinymce').tinymce({
        theme_advanced_toolbar_location : 'top', 
        theme: 'simple'  
       })
```

I'm guessing this is a bug?

**Comment by rtriska** [comment]
Faced with the same issue.
Solution: Just put '//= require tinymce-jquery' above '//= require_tree .'
For example:
'//= require jquery'
'//= require jquery_ujs'
'//= require jquery-ui'
'//= require tinymce-jquery'
'//= require_tree .'

In that case  '<%= tinymce %>' helper works as it should.
